# Generated by Django 4.2.4 on 2023-09-11 07:47

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealShedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='grams',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 9, 1))])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealShedule.meal')),
                ('meal_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealShedule.mealtime')),
            ],
        ),
    ]
